apiVersion: v1
kind: Namespace
metadata:
   name: busybox
   labels:
     name: busybox
---
apiVersion: v1
kind: Service
metadata:
  name: busybox
  namespace: busybox
  labels:
    app: busybox
spec:
  clusterIP: None
  selector:
    app: busybox
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busybox
  namespace: busybox
spec:
  selector:
    matchLabels:
      app: busybox # has to match .spec.template.metadata.labels
  serviceName: "busybox"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: busybox # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo Container is Running ; sleep 3600']
